dist: trusty
language: cpp
sudo: required
matrix:
    include:
        -   os: linux
            compiler: gcc
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - gcc-6
                        - g++-6
                        - build-essential
                        - gfortran
                        - cmake
                        - autoconf
                        - automake
                        - libtool
                        - libboost-all-dev
                        - libblas-dev
                        - liblapack-dev
            env:
                - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
                - LD_LIBRARY_PATH=/usr/local/lib
        -   os: osx
            compiler: clang
            osx_image: xcode9.3
            env:
                - MATRIX_EVAL="CC=clang && CXX=clang++"
before_install:
    - eval "${MATRIX_EVAL}"
script:
    - travis_scripts/build.sh
