sudo: required
dist: trusty
language: cpp
matrix:
    include:
        -   os: linux
            compiler: gcc
            before_install:
                - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
                - sudo apt-get -yq update
                - sudo apt-get -yq install g++-7
                - sudo apt-get -yq install gcc-7
                - sudo apt-get -yq install build-essential
                - sudo apt-get -yq install gfortran
                - sudo apt-get -yq install cmake
                - sudo apt-get -yq install autoconf
                - sudo apt-get -yq install automake
                - sudo apt-get -yq install libtool
                - sudo apt-get -yq install libboost-all-dev
                - sudo apt-get -yq install libblas-dev
                - sudo apt-get -yq install liblapack-dev
            env:
                - MY_CXX=g++-7
                - MY_CC=gcc-7
                - LD_LIBRARY_PATH=/usr/local/lib
        -   os: osx
            compiler: clang
            osx_image: xcode9.3
            env:
                - MY_CXX=clang++
                - MY_CC=clang
install:
    - export CXX=$MY_CXX
    - export CC=$MY_CC
script:
    - travis_scripts/build.sh
