function [P, Q, M, t] = get(bus, G, B, x)
   M = [x(bus.i1PQ:bus.i2PQ); bus.M(bus.i1PV:bus.i2PV); ...
        bus.M(bus.i1SL:bus.i2SL)];
   t = [x(bus.NPQ+1:2*bus.NPQ); x(2*bus.NPQ+bus.NPV+1:end); 0];
   Mc = M .* cos(t);
   Ms = M .* sin(t);
   PSL = Mc(bus.i1SL:bus.i2SL) .* ...
         ( G(bus.i1SL:bus.i2SL,:)*Mc - B(bus.i1SL:bus.i2SL,:)*Ms) ...
       + Ms(bus.i1SL:bus.i2SL) .* ...
         ( G(bus.i1SL:bus.i2SL,:)*Ms + B(bus.i1SL:bus.i2SL,:)*Mc);
   QSL = Mc(bus.i1SL:bus.i2SL) .* ...
         (-G(bus.i1SL:bus.i2SL,:)*Ms - B(bus.i1SL:bus.i2SL,:)*Mc) ...
       + Ms(bus.i1SL:bus.i2SL) .* ...
         ( G(bus.i1SL:bus.i2SL,:)*Mc - B(bus.i1SL:bus.i2SL,:)*Ms);
   P = [bus.P(bus.i1PQ:bus.i2PV);PSL];
   Q = [bus.Q(bus.i1PQ:bus.i2PQ);x(2*bus.NPQ+1:2*bus.NPQ+bus.NPV);QSL];
end
